\connect "checkoutdb"

-- public."Clientes" definition

CREATE TABLE public."Clientes" (
	"Id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"Nome" text NOT NULL,
	"Telefone" text NOT NULL,
	"Email" text NULL,
	CONSTRAINT "PK_Clientes" PRIMARY KEY ("Id")
);

-- public."Enderecos" definition

CREATE TABLE public."Enderecos" (
	"Id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"Cep" text NOT NULL,
	"Logradouro" text NOT NULL,
	"Numero" text NULL,
	"Complemento" text NULL,
	"Cidade" text NOT NULL,
	"Uf" text NOT NULL,
	"Bairro" text NOT NULL,
	"IdCliente" int4 NOT NULL,
	CONSTRAINT "PK_Enderecos" PRIMARY KEY ("Id")
);
CREATE INDEX "IX_Enderecos_IdCliente" ON public."Enderecos" USING btree ("IdCliente");


-- public."Enderecos" foreign keys

ALTER TABLE public."Enderecos" ADD CONSTRAINT "FK_Enderecos_Clientes_IdCliente" FOREIGN KEY ("IdCliente") REFERENCES "Clientes"("Id") ON DELETE CASCADE;

-- public."Transportadoras" definition

CREATE TABLE public."Transportadoras" (
	"Id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"Nome" varchar(100) NOT NULL,
	"NomeServico" varchar(20) NOT NULL,
	"Ativo" bool NOT NULL,
	CONSTRAINT "PK_Transportadoras" PRIMARY KEY ("Id")
);

-- public."TiposPagamento" definition

CREATE TABLE public."TiposPagamento" (
	"Id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"Descricao" varchar(100) NOT NULL,
	"Identificador" varchar(50) NOT NULL,
	CONSTRAINT "PK_TiposPagamento" PRIMARY KEY ("Id")
);

-- public."ValesCompra" definition

CREATE TABLE public."ValesCompra" (
	"Id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"Codigo" varchar(10) NOT NULL,
	"IdCliente" int4 NOT NULL,
	"Valor" float4 NOT NULL,
	"ValorUtilizado" float4 NOT NULL,
	"DataValidade" timestamp NOT NULL,
	"Utilizado" bool NOT NULL,
	CONSTRAINT "PK_ValesCompra" PRIMARY KEY ("Id")
);
CREATE INDEX "IX_ValesCompra_IdCliente" ON public."ValesCompra" USING btree ("IdCliente");


-- public."ValesCompra" foreign keys

ALTER TABLE public."ValesCompra" ADD CONSTRAINT "FK_ValesCompra_Clientes_IdCliente" FOREIGN KEY ("IdCliente") REFERENCES "Clientes"("Id") ON DELETE CASCADE;

--- Insert's 

insert into public."Transportadoras" ("Nome", "NomeServico", "Ativo")
values 
('Correios Brasil','CORREIOS','1'),
('Fedex','FEDEX','1'),
('Jadlog','JADLOG','1'),
('Mercado Envios','MERCADOENVIOS','1');

insert into public."TiposPagamento" ("Descricao", "Identificador")
values
('Cartão de Crédito','CARTAOCREDITO'),
('Vale-Compra','VALECOMPRA');
