\connect "checkoutdb"

-- public."Clientes" definition

CREATE TABLE public."Clientes" (
	"Id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"Nome" text NOT NULL,
	"Telefone" text NOT NULL,
	"Email" text NULL,
	CONSTRAINT "PK_Clientes" PRIMARY KEY ("Id")
);

-- public."Enderecos" definition

CREATE TABLE public."Enderecos" (
	"Id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"Cep" text NOT NULL,
	"Logradouro" text NOT NULL,
	"Numero" text NULL,
	"Complemento" text NULL,
	"Cidade" text NOT NULL,
	"Uf" text NOT NULL,
	"Bairro" text NOT NULL,
	"IdCliente" int4 NOT NULL,
	CONSTRAINT "PK_Enderecos" PRIMARY KEY ("Id")
);
CREATE INDEX "IX_Enderecos_IdCliente" ON public."Enderecos" USING btree ("IdCliente");


-- public."Enderecos" foreign keys

ALTER TABLE public."Enderecos" ADD CONSTRAINT "FK_Enderecos_Clientes_IdCliente" FOREIGN KEY ("IdCliente") REFERENCES "Clientes"("Id") ON DELETE CASCADE;

-- public."Transportadoras" definition

CREATE TABLE public."Transportadoras" (
	"Id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"Nome" varchar(100) NOT NULL,
	"NomeServico" varchar(20) NOT NULL,
	"Ativo" bool NOT NULL,
	CONSTRAINT "PK_Transportadoras" PRIMARY KEY ("Id")
);

--- Insert's 

insert into public."Transportadoras" ("Nome", "NomeServico", "Ativo")
values 
('Correios Brasil','CORREIOS','1'),
('Fedex','FEDEX','1'),
('Jadlog','JADLOG','1'),
('Mercado Envios','MERCADOENVIOS','1');
